// Shared component vocabulary — DESIGN.md §3 (tiers), §6 (state), §11
// (inventory). Every view imports from here rather than hand-rolling.
export { Button, type ButtonTier, type ButtonProps } from './Button'
export { Badge, StatusDot, type Tone, type DotStatus } from './Badge'
export { MomentumBadge } from './MomentumBadge'
export { Panel, PanelHeader, PanelBody } from './Panel'
export { AnimatedDigits } from './AnimatedDigits'
export { SkeletonRows, EmptyBlock, OfflineBlock, ErrorBlock, StaleBanner, AgeStamp } from './state'
export { SrcTag, type Source } from './SrcTag'
export { ConfirmDialog } from './ConfirmDialog'
export { Segmented, type SegmentOption, type SegmentedProps } from './Segmented'
export { DataTable, type Column } from './DataTable'
export { AppShell } from './AppShell'
export { MetricStat } from './MetricStat'
export { Sparkline } from './Sparkline'
export { LabWarnings } from './LabWarnings'
export { LeanBar } from './LeanBar'
export { RuleText } from './RuleText'
export { FiringBadge } from './FiringBadge'
export { ProbBar } from './strategy/ProbBar'
export { ScoreRubric } from './strategy/ScoreRubric'
export { NoulBar } from './strategy/NoulBar'
export { IntentRow } from './strategy/IntentRow'
export { VerdictBadge } from './strategy/VerdictBadge'
export { ParamForm } from './strategy/ParamForm'
